steps:
  # Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$COMMIT_SHA', '--file=./Dockerfile-deploy', '.']

  # Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$COMMIT_SHA']

  # Run database migrations
  - name: 'gcr.io/cloud-builders/npm'
    env:
      - DATABASE_URL=postgresql://admin:SIEHPDATABASE2024@localhost/$BRANCH_NAME?host=/cloudsql/siehp-410023:us-central1:siehp-database-dev
      - SHADOW_DATABASE_URL=postgresql://admin:SIEHPDATABASE2024@localhost/$test?host=/cloudsql/siehp-410023:us-central1:siehp-database-dev
    entrypoint: npx
    args:
      - 'prisma'
      - 'migrate'
      - 'deploy'

  # Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: '/bin/sh'
    args: [
      '-c',
      'gcloud run deploy $REPO_NAME-$BRANCH_NAME --image gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$COMMIT_SHA --region southamerica-east1 --platform managed --port 8080 --allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$COMMIT_SHA'