name: Test and build development

on:
  pull_request:
    branches: [ dev ]

jobs:
  test-and-build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Test the app
        run: npm run test