name: Test and build

on:
  pull_request:
    branches: [ dev, main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    services:
      database-test:
        image: postgres:15.1-alpine
        env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      database:
        image: postgres:15.1-alpine
        env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: local
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        run: npm ci

      - name: Test the app
        run: "npx prisma migrate dev; npm run test:cov"
        env:
          NODE_ENV: test
          SHADOW_DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1:5432/test"
          DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1:5433/local"
          APP_PORT: "8080"
